/**
 * A function call generated by the model.
 */
export class FunctionCall {
	constructor(
		public readonly id: string,
		public readonly callId: string,
		public readonly name: string,
		public readonly args: string,
	) {
		this.name = name
		this.args = args
	}
}
