export enum HookId {
	BEFORE_MESSAGE_RECEIVED = "BEFORE_MESSAGE_RECEIVED",
	AFTER_MESSAGE_RECEIVED = "AFTER_MESSAGE_RECEIVED",
	BEFORE_INFERENCE = "BEFORE_INFERENCE",
	AFTER_INFERENCE = "AFTER_INFERENCE",
	BEFORE_FUNCTION_CALL = "BEFORE_FUNCTION_CALL",
	AFTER_FUNCTION_CALL = "AFTER_FUNCTION_CALL",
	BEFORE_MODEL_RESPONDED = "BEFORE_MODEL_RESPONDED",
	AFTER_MODEL_RESPONDED = "AFTER_MODEL_RESPONDED",
	ON_ERROR = "ON_ERROR",
}
