export enum HookId {
	BEFORE_INFERENCE = "BEFORE_INFERENCE",
	AFTER_INFERENCE = "AFTER_INFERENCE",
	BEFORE_FUNCTION_CALL = "BEFORE_FUNCTION_CALL",
	AFTER_FUNCTION_CALL = "AFTER_FUNCTION_CALL",
	BEFORE_MODEL_MESSAGE = "BEFORE_MODEL_MESSAGE",
	ON_MODEL_MESSAGE = "ON_MODEL_MESSAGE",
}